name: ci

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract branch name
        run: echo "branch=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
        id: extract_branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: fundor333/hugo:${{ steps.extract_branch.outputs.branch }}
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
